steps:
- uses: actions/checkout@v3
- name: Set up JDK 8
  uses: actions/setup-java@v3
  with:
    java-version: '8'
    distribution: 'temurin'
    server-id: github
    settings-path: ${{ github.workspace }}

- name: Publish to GitHub Packages Apache Maven
  run: mvn -B -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= deploy -s ${{ github.workspace }}/settings.xml
  env:
    GITHUB_TOKEN: ${{ github.token }}
